name: Build Eleventy
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@master
        with:
          publish_dir: dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
